input.onLogoEvent(TouchButtonEvent.Pressed, function () {
    basic.showString("fw")
    keyboard.sendString(keyboard.keys(keyboard._Key.up))
    basic.showString("bk")
    keyboard.sendString(keyboard.keys(keyboard._Key.down))
    basic.showString("up")
    keyboard.sendString(keyboard.rawScancode(91))
    basic.showString("dn")
    keyboard.sendString(keyboard.rawScancode(97))
    basic.showString("gL")
    keyboard.sendString(keyboard.keys(keyboard._Key.left))
    basic.showString("tL")
    keyboard.sendSimultaneousKeys("" + keyboard.modifiers(keyboard._Modifier.shift) + keyboard.keys(keyboard._Key.right), false)
    basic.showString("gR")
    keyboard.sendString(keyboard.keys(keyboard._Key.right))
    basic.showString("Tr")
    keyboard.sendSimultaneousKeys("" + keyboard.modifiers(keyboard._Modifier.shift) + keyboard.keys(keyboard._Key.left), false)
    basic.showString("lu")
    keyboard.sendSimultaneousKeys("" + keyboard.modifiers(keyboard._Modifier.shift) + keyboard.keys(keyboard._Key.down), false)
    basic.showString("ld")
    keyboard.sendSimultaneousKeys("" + keyboard.modifiers(keyboard._Modifier.shift) + keyboard.keys(keyboard._Key.up), false)
})
keyboard.startKeyboardService()
keyboard.setEventsPerSecond(1)
